### login
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "username": "manager",
  "password": "123456"
}

> {%
    client.global.set("token", response.body.data.token)
    console.log("Token:", client.global.get("token"));
%}

### Get slot
GET http://localhost:8080/api/rooms
Authorization: Bearer {{token}}

> {%
    client.global.set("slotId", response.body.data.content[0].slots[0].id)
    client.log("slotId =", client.global.get("slotId"))
%}

### book slot
POST http://localhost:8080/api/booking/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "slotId": "{{slotId}}"
}

> {%
    client.global.set("paymentUrl", response.body.data.paymentUrl)
    client.log("paymentUrl =", client.global.get("paymentUrl"))
%}

### latest payment url
GET http://localhost:8080/api/payment/booking/pending
Authorization: Bearer {{token}}

### current booking
GET http://localhost:8080/api/booking/current
Authorization: Bearer {{token}}

### booking history
GET http://localhost:8080/api/booking/history
Authorization: Bearer {{token}}