### book slot
POST http://localhost:8080/api/booking?slotId={{slotId}}
Authorization: Bearer {{token}}

> {%
    client.global.set("paymentUrl", response.body.data)
    client.log("paymentUrl =", client.global.get("paymentUrl"))
 %}