### all checkin
GET http://localhost:8080/api/slots?status=CHECKIN
Authorization: Bearer {{token}}

> {%
    client.global.set("slotid", response.body.data.content[0].id)
    client.log("slotid =", client.global.get("slotid"))
%}

### checkin
POST http://localhost:8080/api/slots/checkin/{{slotId}}
Authorization: Bearer {{token}}