POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "username": "resident",
  "password": "resident"
}

> {%
 client.global.set("token", response.body.data.token)
 client.log(token)
 %}

###

GET http://localhost:8080/api/semesters
Authorization: Bearer {{token}}

###
GET http://localhost:8080/api/semesters/06718179-74e5-4345-8f9d-c4365345f44d
Authorization: Bearer {{token}}

###
GET http://localhost:8080/api/semesters/current
Authorization: Bearer {{token}}

###
POST http://localhost:8080/api/semesters
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "SU26",
  "startDate": "2026-01-01",
  "endDate": "2026-04-01"
}

###
GET http://localhost:8080/api/rooms?totalSlot=4
Authorization: Bearer {{token}}