spring:
  application:
    name: capstone
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/capstone?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: A3F9C7D28E45B671F04A98D3BC56E21F7D8A32B5C4E690FA1B3D7E82564F90CD
  expiration: 86400000

vnpay:
  secret: YFRG1AKBDYW9CHRMWM50DO1X2PA5RG6E
  tmncode: LLO1RUC8

logging:
  level:
    org.springframework.web: debug
    org.hibernate.jdbc.bind: trace