### Login
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "username": "resident",
  "password": "resident"
}

> {%
    client.global.set("token", response.body.data.token)
    console.log("Token =", client.global.get("token"));
%}

### Get all rooms
GET http://localhost:8080/api/rooms
Authorization: Bearer {{token}}

> {%
    client.global.set("roomId", response.body.data.content[0].id)
    client.log("roomId =", client.global.get("roomId"))
%}

### update room
POST http://localhost:8080/api/rooms/{{roomId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "floor": 1,
  "roomNumber": "A101",
  "totalSlot": 4
}

### Get rooms-matching
GET http://localhost:8080/api/rooms-matching
Authorization: Bearer {{token}}

> {%
 client.global.set("roomId", response.body.data[0].id)
 client.log("roomId =", client.global.get("roomId"))
 %}

### Get room detail
GET http://localhost:8080/api/rooms/{{roomId}}
Authorization: Bearer {{token}}

### Get room users
GET http://localhost:8080/api/rooms/{{roomId}}/users
Authorization: Bearer {{token}}